### ISSUE TITLE
Bug beim Finden der aktuellen Position

### ISSUE THREAD

**Issue by AlexRockstroh** [AlexRockstroh/projectMap#1]
Beim erstmaligen Freigeben der Permissions für die Ortung, kann es die aktuelle Position nicht bestimmen und die Anfrage liefert ein null object zurück. Aktuelle "Lösung": Kurz zurück auf die Homepage navigieren und wieder auf die Map, dann geht es

**Comment by FoxBanri** [comment]
Mögliche Lösung wäre eine Refresh-Button. Würde die Endlosschleife umgehen und man müsste nur einmal klicken.
